export const MOVIES_CACHE_KEY = 'movies'
export const TMDB_MOVIE_CACHE_KEY = 'movie/tmdb'
export const YTS_MOVIE_CACHE_KEY = 'movie/yts'
export const YTS_MOVIE_SUGGESTION_CACHE_KEY = 'movie/yts/suggestions'
export const INFINITE_MOVIES_CACHE_KEY = 'infinite_movies'
